# Generated by Django 4.1.3 on 2023-04-03 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryActivity",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity", models.CharField(blank=True, max_length=255, null=True)),
                ("hospitalID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inventory_activity_hospitalID",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory Activities",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bloodGroup",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "Opositive"),
                            ("O-", "Onegative"),
                            ("AB+", "Abpositive"),
                            ("AB-", "Abnegative"),
                            ("A+", "Apositive"),
                            ("A-", "Anegative"),
                            ("B+", "Bpositive"),
                            ("B-", "Bnegative"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bloodUnits",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("hospitalID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inventory_hospitalID",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory",
            },
        ),
    ]
