# Generated by Django 4.1.3 on 2023-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='ABNegative',
            new_name='bloodUnits',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ABPositive',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ANegative',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='APositive',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='BNegative',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='BPositive',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ONegative',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='OPositive',
        ),
        migrations.AddField(
            model_name='inventory',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'Opositive'), ('O-', 'Onegative'), ('AB+', 'Abpositive'), ('AB-', 'Abnegative'), ('A+', 'Apositive'), ('A-', 'Anegative'), ('B+', 'Bpositive'), ('B-', 'Bnegative')], max_length=255, null=True),
        ),
    ]
