# Generated by Django 4.1.3 on 2023-04-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryactivity",
            old_name="hospitalID",
            new_name="bloodGroup",
        ),
        migrations.AlterField(
            model_name="inventoryactivity",
            name="activity",
            field=models.TextField(blank=True, null=True),
        ),
    ]
