# Generated by Django 4.1.3 on 2023-04-13 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0002_rename_bloodunits_inventory_abnegative_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_hospitalID",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
