# Generated by Django 4.1.3 on 2023-04-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_rename_hospitalid_inventoryactivity_bloodgroup_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryactivity",
            options={"verbose_name_plural": "Inventory Activity"},
        ),
    ]
