# Generated by Django 4.1.3 on 2023-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_abnegative_inventory_bloodunits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
