# Generated by Django 4.1.4 on 2023-06-18 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_alter_inventoryactivity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodUnits', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('appointmentID', models.CharField(blank=True, max_length=255, null=True)),
                ('hospitalID', models.CharField(blank=True, max_length=255, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_item_donor', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryitem_inventory', to='hospital.inventory')),
            ],
            options={
                'verbose_name_plural': 'Inventory Item',
            },
        ),
    ]
