# Generated by Django 4.1.4 on 2023-06-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_inventoryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryactivity',
            options={'ordering': ('-pkid',), 'verbose_name_plural': 'Inventory Activity'},
        ),
    ]
