# Generated by Django 4.1.3 on 2023-04-26 10:30

import apps.common.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.common.media.avatar_path
            ),
        ),
    ]
