# Generated by Django 4.1.3 on 2023-04-26 10:49

import apps.common.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/images/profile/avatar__1.png",
                null=True,
                upload_to=apps.common.media.avatar_path,
            ),
        ),
    ]
