# Generated by Django 4.1.3 on 2023-05-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_address_user_city_user_lga_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="postalCode",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
