# Generated by Django 4.1.3 on 2023-05-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_postalcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
    ]
