# Generated by Django 4.1.3 on 2023-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="lga",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="postalCode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
