# Generated by Django 4.1.4 on 2023-06-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_address_alter_user_lga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_login',
            field=models.BooleanField(default=False),
        ),
    ]
