# Generated by Django 4.2.1 on 2023-06-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_email_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_recovering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lastDonationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
