# Generated by Django 4.2.1 on 2023-06-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_in_recovering_user_lastdonationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='in_recovering',
            new_name='in_recovery',
        ),
    ]
