# Generated by Django 4.2.1 on 2023-08-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_in_recovering_user_in_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacypolicy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=True),
        ),
    ]
