# Generated by Django 4.2.1 on 2023-06-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_profile_hospitalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
