# Generated by Django 4.2.1 on 2023-06-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_profile_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bloodGroup',
        ),
    ]
