# Generated by Django 4.2.1 on 2023-06-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_profile_hospitalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
