# Generated by Django 4.2.1 on 2023-07-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_profile_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
