# Generated by Django 4.0.5 on 2023-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_alter_profile_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userAvatarPublicId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
