# Generated by Django 4.0.5 on 2023-07-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_profile_useravatarpublicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hospitalImagePublicId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospitalLogo',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dzve1ooxl/image/upload/v1688642512/Medexer-API/media/profile/logo_no_name_jsgbpp.png', max_length=255, null=True, upload_to='Medexer-API/media/profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospitalLogoPublicId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospitalImage',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dzve1ooxl/image/upload/v1688642315/Medexer-API/media/profile/hospital__2_c4joyq.jpg', max_length=255, null=True, upload_to='Medexer-API/media/profile/'),
        ),
    ]
