# Generated by Django 4.0.5 on 2023-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_profile_hospitalimagepublicid_profile_hospitallogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hospitalImage',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dzve1ooxl/image/upload/v1688642315/Medexer-API/media/hospital-profile/hospital__2_c4joyq.jpg', max_length=255, null=True, upload_to='Medexer-API/media/hospital-profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospitalLogo',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dzve1ooxl/image/upload/v1688642512/Medexer-API/media/hospital-profile/logo_no_name_jsgbpp.png', max_length=255, null=True, upload_to='Medexer-API/media/hospital-profile/'),
        ),
    ]
