# Generated by Django 4.0.5 on 2023-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_alter_profile_hospitalimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hospitalImagePublicId',
            field=models.CharField(blank=True, default='00000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospitalLogoPublicId',
            field=models.CharField(blank=True, default='00000', max_length=255, null=True),
        ),
    ]
