# Generated by Django 4.1.3 on 2023-04-15 00:49

import apps.common.media
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowYourBusiness",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cacRegistrationID",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("websiteUrl", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.media.kyb_document_path,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "identificationType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VOTERCARD", "Votercard"),
                            ("NATIONALIDENTITYCARD", "Nationalidentitycard"),
                            ("CACCERTIFICATE", "Caccertificate"),
                        ],
                        default="CACCERTIFICATE",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("hospitalID", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "Know Your Businesses",
            },
        ),
        migrations.CreateModel(
            name="KnowYourCustomer",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bloodGroup",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "Opositive"),
                            ("O-", "Onegative"),
                            ("AB+", "Abpositive"),
                            ("AB-", "Abnegative"),
                            ("A+", "Apositive"),
                            ("A-", "Anegative"),
                            ("B+", "Bpositive"),
                            ("B-", "Bnegative"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "genotype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AA", "Aa"),
                            ("AS", "As"),
                            ("AC", "Ac"),
                            ("SS", "Ss"),
                            ("SC", "Sc"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("haveDonatedBlood", models.BooleanField(default=False)),
                (
                    "lastBloodDonationTime",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hasTattos", models.BooleanField(default=False)),
                (
                    "identificationType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VOTERCARD", "Votercard"),
                            ("NATIONALIDENTITYCARD", "Nationalidentitycard"),
                            ("CACCERTIFICATE", "Caccertificate"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "documentUploadCover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.media.kyc_document_path,
                    ),
                ),
                (
                    "documentUploadRear",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.media.kyc_document_path,
                    ),
                ),
                ("donorID", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
