# Generated by Django 4.1.3 on 2023-04-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowyourbusiness",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="knowyourbusiness",
            name="cacRegistrationID",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="knowyourbusiness",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowyourbusiness",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="knowyourbusiness",
            name="websiteUrl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="knowyourbusiness",
            name="identificationType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VOTERCARD", "Votercard"),
                    ("NATIONALIDENTITYCARD", "Nationalidentitycard"),
                    ("CACCERTIFICATE", "Caccertificate"),
                ],
                default="CACCERTIFICATE",
                max_length=255,
                null=True,
            ),
        ),
    ]
