# Generated by Django 4.1.3 on 2023-04-04 15:03

import apps.common.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_knowyourbusiness_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowyourbusiness",
            name="documentUploadCover",
        ),
        migrations.RemoveField(
            model_name="knowyourbusiness",
            name="documentUploadRear",
        ),
        migrations.AlterField(
            model_name="knowyourbusiness",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.common.media.kyb_document_path
            ),
        ),
    ]
