# Generated by Django 4.2.1 on 2023-06-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_knowyourbusiness_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyourbusiness',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowyourbusiness',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowyourcustomer',
            name='isRecentVaccineRecipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowyourcustomer',
            name='tobaccoUsage',
            field=models.BooleanField(default=False),
        ),
    ]
