# Generated by Django 4.2.1 on 2023-06-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_knowyourbusiness_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyourbusiness',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowyourbusiness',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
