# Generated by Django 4.0.5 on 2023-07-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_knowyourbusiness_city_knowyourbusiness_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='documentUploadCover',
            field=models.ImageField(blank=True, null=True, upload_to='Medexer-API/media/kyc/'),
        ),
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='documentUploadRear',
            field=models.ImageField(blank=True, null=True, upload_to='Medexer-API/media/kyc'),
        ),
    ]
