# Generated by Django 4.1.3 on 2023-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hospitalID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
