# Generated by Django 4.1.3 on 2023-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0003_alter_notification_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="compaintID",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPENED", "Opened"),
                    ("CLOSED", "Closed"),
                    ("IN_PROGRESS", "In Progress"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
