# Generated by Django 4.1.3 on 2023-04-11 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0004_alter_complaint_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaint_hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
