# Generated by Django 4.1.3 on 2023-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_complaint_compaintid_complaint_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="hospital",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="compaintID",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
