# Generated by Django 4.1.3 on 2023-04-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0006_complaint_hospital"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="compaintID",
            new_name="complaintID",
        ),
    ]
