# Generated by Django 4.1.3 on 2023-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0009_rename_status_complainthistory_updatetype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={"ordering": ["pkid"]},
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="message",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPENED", "Opened"),
                    ("CLOSED", "Closed"),
                    ("REOPENED", "Reopened"),
                    ("IN_PROGRESS", "In Progress"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
