# Generated by Django 4.1.3 on 2023-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0010_alter_complaint_options_remove_complaint_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notificationType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DONOR", "Donor"),
                    ("HOSPITAL", "Hospital"),
                    ("DONATION", "Donation"),
                    ("MEDEXER", "Medexer"),
                    ("COMPLAINT", "Complaint"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
