# Generated by Django 4.1.3 on 2023-04-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0012_notification_is_read_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notificationType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPOINTMENT", "Appointment"),
                    ("HOSPITAL", "Hospital"),
                    ("DONATION", "Donation"),
                    ("APP_UPDATE", "App Update"),
                    ("ADMIN", "Admin"),
                    ("COMPLAINT", "Complaint"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
