# Generated by Django 4.1.3 on 2023-04-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0013_alter_notification_notificationtype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={"ordering": ("-pkid",)},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-pkid",)},
        ),
    ]
