# Generated by Django 4.1.3 on 2023-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
