# Generated by Django 4.1.3 on 2023-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_integration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='accessKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
