# Generated by Django 4.1.3 on 2023-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_complainthistory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='authorType',
            field=models.CharField(blank=True, choices=[('HOSPITAL', 'Hospital'), ('DONOR', 'Donor'), ('ADMIN', 'Admin')], max_length=255, null=True),
        ),
    ]
