# Generated by Django 4.1.3 on 2023-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
