# Generated by Django 4.1.3 on 2023-04-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0003_alter_appointment_donor_alter_appointment_hospital"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ("-pkid",)},
        ),
    ]
