# Generated by Django 4.1.3 on 2023-04-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0004_appointmentactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="isDonated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="donationactivity",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="donation_activity",
                to="donor.appointment",
            ),
        ),
    ]
