# Generated by Django 4.1.3 on 2023-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_appointment_donationdate_appointment_pints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pints',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
