# Generated by Django 4.1.4 on 2023-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_alter_appointment_pints'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='isDonated',
            field=models.BooleanField(default=False),
        ),
    ]
