# Generated by Django 4.1.4 on 2023-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_appointment_ispaid_alter_appointment_isdonated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
