# Generated by Django 4.2.1 on 2023-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_appointment_appointmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isForAdult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visitRecipient',
            field=models.BooleanField(default=False),
        ),
    ]
