# Generated by Django 4.0.5 on 2023-07-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_rename_isforadult_appointment_getnotifiedonblooduse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='visitRecipient',
            new_name='isForAdult',
        ),
    ]
