# Generated by Django 4.2.1 on 2023-06-28 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hiv', models.CharField(blank=True, max_length=255, null=True)),
                ('hepatitisB', models.CharField(blank=True, max_length=255, null=True)),
                ('hepatitisC', models.CharField(blank=True, max_length=255, null=True)),
                ('vdrl', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodPressure', models.CharField(blank=True, max_length=255, null=True)),
                ('bodyTemperature', models.CharField(blank=True, max_length=255, null=True)),
                ('genotype', models.CharField(blank=True, max_length=255, null=True)),
                ('pcv', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_data_author', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_data_donor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical Test',
            },
        ),
    ]
