# Generated by Django 4.2.1 on 2023-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'Opositive'), ('O-', 'Onegative'), ('AB+', 'Abpositive'), ('AB-', 'Abnegative'), ('A+', 'Apositive'), ('A-', 'Anegative'), ('B+', 'Bpositive'), ('B-', 'Bnegative')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'Aa'), ('AS', 'As'), ('AC', 'Ac'), ('SS', 'Ss'), ('SC', 'Sc')], max_length=255, null=True),
        ),
    ]
