# Generated by Django 4.2.1 on 2023-06-29 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0009_appointment_isforadult_appointment_visitrecipient'),
        ('medical_data', '0002_alter_medicaltest_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_data_appointment', to='donor.appointment'),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_data_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_data_donor', to=settings.AUTH_USER_MODEL),
        ),
    ]
