# Generated by Django 4.2.1 on 2023-06-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0003_medicaltest_appointment_alter_medicaltest_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'ordering': ('-pkid',), 'verbose_name_plural': 'Medical Test'},
        ),
    ]
